### PR TITLE
Script errors in fixtures are not reported in the parent window.

### PR DESCRIPTION
**Pull request by jagoda**
When using karma+mocha+js-fixtures to do UI testing, I noticed that tests that depend on the results of UI events in a fixture do not report the failures -- they just timeout. The problem seems to be that assertions that execute in an event handler belonging to the fixture document are caught by the fixture window's `onerror` handler and not reported to the parent (where mocha is listening for uncaught errors). For example, assuming jQuery is present, the following UI code would cause the following test to report a timeout rather than an assertion failure:

UI code:

```
<button id='toggle'>Toggle</button>
<div id='target' style='display:none'>Target</div>
<script>
$('#toggle').click(function(){
    // Adding this comment to demonstrate the intent of the test while maintaining
    // the failure condition.
    // $('#target').toggle();
});
</script>
```

Test code:

```
it("displays the div if the button is clicked", function(done){
    var $ = fixtures.window().$;
    var button = $('#toggle');

    button.one('click', function(){
        var div = $('#target');
        expect(div.is(':visible')).to.be(true);
        done();
    });

    button.click();
});
```

This code builds upon the code for #19.

### CODE REVIEW

**Comment by anacronw** [comment]
Wow, this feature seems like a necessity - I had never thought of this case.

I think it actually makes sense to turn it on by default - in fact I see no reason to make this configurable.  Perhaps js-fixtures should indicate in some way that the error is coming from the child window instead.  What do you think?

Is there a way to separate the visibility concerns away from the error throwing? (https://github.com/jagoda/js-fixtures/commit/60305001c1982b9ed54cc625b71cd57a836eb9ca#diff-21c86aaa4ceb2199139862a7abfa6dc4R70)

**Comment by jagoda** [comment]
Ya, I was also leaning towards making the error capturing a core behavior. However, I'm not sure how to separate the error capturing from the visibility. I found that Firefox would not report the errors as expected unless the frame was visible. I'm not sure why this is since I couldn't find any documentation indicating that this should (or does) happen. Chrome worked as expected regardless of the frame's visibility. In the end, it seemed to me that the options where to either make the fixture frame always visible or to make error capturing configurable. Thoughts?

Making the error message indicate that the error came from the child should be pretty easy.

**Comment by anacronw** [comment]
I just realized maybe I can hide the iframe via "opacity: 0" in firefox, it passes the tests you've written in the previous PR.

If that works for you, then I think the issue is side stepped.

**Comment by jagoda** [comment]
Nice, I hadn't thought of that. The opacity trick works great for my needs. It seems to me that if the opacity trick is used, then the visibility config option is no longer really useful. The reworked changes make it so that visibility and error capturing work in Firefox and Chrome without any additional config. I have no easy way to test on IE at the moment (I just have Linux at home), but maybe you could try the changes out on IE for me?

**Comment by anacronw** [comment]
Yeah absolutely,

I will have to get back to you in a couple days, currently on vacation

**Comment by jagoda** [comment]
I suppose you may still be on vacation, but if not, any chance you could take a look at the latest changes?

**Comment by anacronw** [comment]
Thanks, very elegant solution.

I'm still on vacation and was w/o internet for a couple of days, thanks for your patience

**Comment by jagoda** [comment]
Cool, thanks.

**Comment by anacronw** [comment]
I'll publish a new version on npm shortly

**Pull request merged**
