### PR TITLE
re-implement sandbox

### PR DESCRIPTION
**Pull request by rickeyvisinski-kanban**
I just migrated from Jasmine-jquery and had used the sandbox feature quite a bit.  Here is my re-implementation.

### CODE REVIEW

**Comment by anacronw** [comment]
Hi - could you add tests for this?

Perhaps I should've taken a 2nd look at sandbox, it seems more useful than I thought.

**Comment by rickeyvisinski-kanban** [comment]
All set

**Comment by anacronw** [comment]
The project is currently running all fixtures through the iframe to reduce interaction effects w/ the test runner.  It seems as if this implementation of the sandbox creates elements alongside the iframe.  I think it would be more useful to have it quickly create fixtures inside the iframe through the same syntax.

**Comment by rickeyvisinski-kanban** [comment]
Ok, i will take a look at just patching appendSet instead.

**Comment by anacronw** [comment]
Hi @rickeyvisinski-kanban, so sorry to have missed your PR.

As I intentionally switched away from injecting fixtures on the same document, into the iframe implementation, I don't wish to go back.

I have re-implemented the sandbox feature such that if you provide it a js object into the method, it will add it to the fixtures container (https://github.com/badunk/js-fixtures/commit/9625793604967b1b595a6037c3108b00a64e2290)

Please let me know if this fixes your needs

Thanks!

**Pull request closed without merging**
