### PR TITLE
Want to use this code without the browser.

### PR DESCRIPTION
**Pull request by jkresner**
- Since no http/ajax is available, revert to using the file system to load html files.

! However need to require jquery (code is still blowing with no reference to jquery object)

### CODE REVIEW

**Comment by anacronw** [comment]
this is an interesting idea, I had never attempted to do this via node, I'll review the code and get back soon.

**Comment by anacronw** [comment]
I removed the jquery dependencies from the specs and the library itself.  Could you try another pull?

**Comment by jkresner** [comment]
Hey Duncan sorry for late reply. We've moved off JSDom and opted for PhantomJS instead, so the original version works for us. I was still having problems on JSDom even without jQuery. Appreciate you modifying the scripts. Thanks.

**Comment by anacronw** [comment]
no problem, thanks for the jquery pointer anyways - there really was no reason for me to have a dependency on that.

Good luck

**Pull request closed without merging**
